# /etc/NetworkManager/conf.d/00-use-dnsmasq.conf
# from: https://fedoramagazine.org/using-the-networkmanagers-dnsmasq-plugin/
# This enabled the dnsmasq plugin.
[main]
dns=dnsmasq
rc-manager=auto
# Note: the only way how to manage properly /etc/resolv.conf was:
#  systemctl disable systemd-resolved
#  systemctl mask systemd-resolved
#  rm /etc/resolv.conf  # remove symlink
#  systemctl restart NetworkManager
 
