# adapted from: https://fedoramagazine.org/using-the-networkmanagers-dnsmasq-plugin/
addn-hosts=/etc/hosts
#server=78.157.167.7
#server=78.157.167.57
#server=2a02:d8a0:1::
log-queries
log-facility=/var/log/dnsmasq-nm.log
# filter-AAAA
# trailing '#' is not comment, but NULL address
#address=/.mozilla.net/#
address=/.firefox.com/#
address=/.settings.services.mozilla.com/#
address=/.mozilla.org/#
address=/mozilla.map.fastly.net/#
address=/.gravatar.com/#
address=/cloudflare-dns.com/#
